# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newSignUp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(617, 454)
        SignUp.setStyleSheet("background:rgb(237, 212, 0)")
        self.gridLayout = QtWidgets.QGridLayout(SignUp)
        self.gridLayout.setObjectName("gridLayout")
        self.reg_visitor_button = QtWidgets.QPushButton(SignUp)
        self.reg_visitor_button.setStyleSheet("background:rgb(186, 189, 182)")
        self.reg_visitor_button.setObjectName("reg_visitor_button")
        self.gridLayout.addWidget(self.reg_visitor_button, 11, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 14, 3, 1, 1)
        self.reg_conf_line_2 = QtWidgets.QLineEdit(SignUp)
        self.reg_conf_line_2.setStyleSheet("background:rgb(238, 238, 236)")
        self.reg_conf_line_2.setObjectName("reg_conf_line_2")
        self.gridLayout.addWidget(self.reg_conf_line_2, 10, 3, 1, 1)
        self.reg_email_line = QtWidgets.QLineEdit(SignUp)
        self.reg_email_line.setStyleSheet("background:rgb(238, 238, 236)")
        self.reg_email_line.setObjectName("reg_email_line")
        self.gridLayout.addWidget(self.reg_email_line, 4, 3, 1, 1)
        self.reg_username_line_2 = QtWidgets.QLineEdit(SignUp)
        self.reg_username_line_2.setStyleSheet("background:rgb(238, 238, 236)")
        self.reg_username_line_2.setObjectName("reg_username_line_2")
        self.gridLayout.addWidget(self.reg_username_line_2, 6, 3, 1, 1)
        self.reg_pass_line = QtWidgets.QLineEdit(SignUp)
        self.reg_pass_line.setStyleSheet("background:rgb(238, 238, 236)")
        self.reg_pass_line.setObjectName("reg_pass_line")
        self.gridLayout.addWidget(self.reg_pass_line, 8, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 3)
        self.reg_staff_button = QtWidgets.QPushButton(SignUp)
        self.reg_staff_button.setStyleSheet("background:rgb(186, 189, 182)")
        self.reg_staff_button.setObjectName("reg_staff_button")
        self.gridLayout.addWidget(self.reg_staff_button, 11, 3, 1, 2)

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Dialog"))
        self.reg_visitor_button.setText(_translate("SignUp", "Register Visitor"))
        self.label_2.setText(_translate("SignUp", "Email"))
        self.label_5.setText(_translate("SignUp", "Password"))
        self.label_3.setText(_translate("SignUp", "Confirm Password"))
        self.label_4.setText(_translate("SignUp", "Username"))
        self.label.setText(_translate("SignUp", "Atlanta Zoo Registration"))
        self.reg_staff_button.setText(_translate("SignUp", "Register Staff"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUp = QtWidgets.QDialog()
    ui = Ui_SignUp()
    ui.setupUi(SignUp)
    SignUp.show()
    sys.exit(app.exec_())

