# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visitorsearchAnimals.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from loadData import *
from Visitor.visitoranimalDetail import Ui_animalDetail as animalDetail
from Visitor.visitorexhibitDetail import Ui_exhibitDetail

class Ui_searchAnimals(object):
    def __init__(self, username):
        object.__init__(self)
        self.connection = pymysql.connect(host = 'academic-mysql.cc.gatech.edu',password = 'Al5qCS2i', user = 'cs4400_group59', db='cs4400_group59')
        self.username = username
        self.sqlheaderList = ['Name', 'Species', 'Age', 'Type', 'Exhibit']
        self.orderdict = {0: "asc", 1: "asc", 2: "asc", 3: "asc", 4: "asc"}

    def sortbyHeader(self):
        i = self.tableheader.sortIndicatorSection()
        query = ("select * from cs4400_group59.ANIMAL order by {} {};").format(self.sqlheaderList[i], self.orderdict[i])
        if self.orderdict[i] == "asc":
            self.orderdict[i]="desc"
        else:
            self.orderdict[i] = "asc"

        cursor=self.connection.cursor()
        cursor.execute(query)
        result=cursor.fetchall()
        loadTable(self.animalTable, result, ['Name', 'Species', 'Age', 'Type', 'Exhibit'], 5)
        cursor.close()

    def loadBox(self):
        cursor = self.connection.cursor()
        cursor.execute("USE cs4400_group59;")
        query = "SELECT Name from EXHIBIT; "
        cursor.execute(query)
        result = cursor.fetchall()
        loadExhibit(self.exhibitBox, result)

    def animalSearch(self):
        nameToStr = self.nameEdit.text()
        speciesToStr = self.speciesEdit.text()
        minToInt = self.aminBox.value()
        maxToInt = self.amaxBox.value()
        typeToStr = self.typeBox.currentText()
        exhibitToString = self.exhibitBox.currentText()

        query = "SELECT * from cs4400_group59.ANIMAL where name like '%{}%' AND species like '%{}%' AND age >= {} AND age <= {} AND type like '%{}%' and exhibit like '%{}%';".format(
            nameToStr, speciesToStr, minToInt, maxToInt, typeToStr, exhibitToString)
        # print(query)
        cursor = self.connection.cursor()
        cursor.execute("USE cs4400_group59;")
        cursor.execute(query)
        result = cursor.fetchall()
        loadTable(self.animalTable, result, ['Name', 'Species', 'Age', 'Type', 'Exhibit'], 5)
        cursor.close()

    def exhibitDetail(self):
        exhibit = self.animalTable.selectedItems()
        exhibit = exhibit[4].text()
        self.detailDialog = QtWidgets.QDialog()
        self.ui = Ui_exhibitDetail(exhibit, self.username)
        self.ui.setupUi(self.detailDialog)
        self.detailDialog.show()

    #
    # def detailShow(self):
    #     animal = self.animalTable.selectedItems()
    #     animalItems = []
    #     for i in animal:
    #         animalItems.append(i.text())
    #     self.detailWindow = QtWidgets.QDialog()
    #     self.ui = animalDetail(animalItems)
    #     self.ui.setupUi(self.detailWindow)
    #     self.detailWindow.show()
    def loadAnimal(self):
        cursor = self.connection.cursor()
        query = "select * from cs4400_group59.ANIMAL"
        cursor.execute(query)
        result = cursor.fetchall()
        loadTable(self.animalTable, result, ['Name', 'Species', 'Age', 'Type', 'Exhibit'], 5)
        cursor.close()

    def setupUi(self, searchAnimals):
        searchAnimals.setObjectName("searchAnimals")
        searchAnimals.resize(588, 461)
        searchAnimals.setStyleSheet("background:rgb(237, 212, 0)")
        self.gridLayout = QtWidgets.QGridLayout(searchAnimals)
        self.gridLayout.setObjectName("gridLayout")
        self.speciesEdit = QtWidgets.QLineEdit(searchAnimals)
        self.speciesEdit.setStyleSheet("background:rgb(238, 238, 236)")
        self.speciesEdit.setObjectName("speciesEdit")
        self.gridLayout.addWidget(self.speciesEdit, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.typeLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeLabel.setFont(font)
        self.typeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.typeLabel.setObjectName("typeLabel")
        self.gridLayout.addWidget(self.typeLabel, 5, 4, 1, 1)
        self.animalTable = QtWidgets.QTableWidget(searchAnimals)
        self.animalTable.setStyleSheet("background:rgb(238, 238, 236)")
        self.animalTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.animalTable.setObjectName("animalTable")
        self.animalTable.setColumnCount(5)
        self.animalTable.setRowCount(0)
        self.animalTable.doubleClicked.connect(self.exhibitDetail)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.animalTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.animalTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.animalTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.animalTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.animalTable.setHorizontalHeaderItem(4, item)
        self.animalTable.horizontalHeader().setVisible(True)
        self.animalTable.horizontalHeader().setCascadingSectionResizes(True)
        self.animalTable.horizontalHeader().setHighlightSections(False)
        self.animalTable.horizontalHeader().setSortIndicatorShown(True)
        self.animalTable.horizontalHeader().setStretchLastSection(True)
        self.animalTable.verticalHeader().setVisible(True)
        self.animalTable.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.animalTable, 9, 1, 1, 6)
        self.ageLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ageLabel.setFont(font)
        self.ageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ageLabel.setObjectName("ageLabel")
        self.gridLayout.addWidget(self.ageLabel, 4, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.speciesLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.speciesLabel.setFont(font)
        self.speciesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.speciesLabel.setObjectName("speciesLabel")
        self.gridLayout.addWidget(self.speciesLabel, 5, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(searchAnimals)
        self.nameEdit.setStyleSheet("background:rgb(238, 238, 236)")
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 4, 2, 1, 1)
        self.searchButton = QtWidgets.QPushButton(searchAnimals)
        self.searchButton.setStyleSheet("background:rgb(186, 189, 182)")
        self.searchButton.setObjectName("searchButton")
        self.searchButton.clicked.connect(self.animalSearch)
        self.gridLayout.addWidget(self.searchButton, 7, 4, 1, 2)
        self.detailLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.detailLabel.setFont(font)
        self.detailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailLabel.setObjectName("detailLabel")
        self.gridLayout.addWidget(self.detailLabel, 1, 1, 1, 6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 7, 1, 1)
        self.aminBox = QtWidgets.QSpinBox(searchAnimals)
        self.aminBox.setStyleSheet("background:rgb(238, 238, 236)")
        self.aminBox.setMaximum(5000)
        self.aminBox.setObjectName("aminBox")
        self.gridLayout.addWidget(self.aminBox, 4, 5, 1, 1)
        self.amaxBox = QtWidgets.QSpinBox(searchAnimals)
        self.amaxBox.setStyleSheet("background:rgb(238, 238, 236)")
        self.amaxBox.setMaximum(5000)
        self.amaxBox.setObjectName("amaxBox")
        self.gridLayout.addWidget(self.amaxBox, 4, 6, 1, 1)
        self.exhibitLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exhibitLabel.setFont(font)
        self.exhibitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exhibitLabel.setObjectName("exhibitLabel")
        self.gridLayout.addWidget(self.exhibitLabel, 6, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 4, 1, 1, 1)
        self.exhibitBox = QtWidgets.QComboBox(searchAnimals)
        self.exhibitBox.setStyleSheet("background:rgb(238, 238, 236)")
        self.exhibitBox.setObjectName("exhibitBox")
        self.exhibitBox.addItem("")
        self.exhibitBox.setItemText(0, "")
        self.gridLayout.addWidget(self.exhibitBox, 6, 2, 1, 1)
        self.amaxLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.amaxLabel.setFont(font)
        self.amaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amaxLabel.setObjectName("amaxLabel")
        self.gridLayout.addWidget(self.amaxLabel, 2, 6, 1, 1)
        self.typeBox = QtWidgets.QComboBox(searchAnimals)
        self.typeBox.setAutoFillBackground(False)
        self.typeBox.setStyleSheet("background:rgb(238, 238, 236)")
        self.typeBox.setObjectName("typeBox")
        self.typeBox.addItem("")
        self.typeBox.setItemText(0, "")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.gridLayout.addWidget(self.typeBox, 5, 5, 1, 2)
        self.aminLabel = QtWidgets.QLabel(searchAnimals)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.aminLabel.setFont(font)
        self.aminLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aminLabel.setObjectName("aminLabel")
        self.gridLayout.addWidget(self.aminLabel, 2, 5, 1, 1)
        self.zooLabel = QtWidgets.QLabel(searchAnimals)
        self.zooLabel.setObjectName("zooLabel")
        self.gridLayout.addWidget(self.zooLabel, 2, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 11, 0, 1, 1)
        self.backButton = QtWidgets.QPushButton(searchAnimals)
        self.backButton.setStyleSheet("background:rgb(186, 189, 182)")
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 10, 6, 1, 1)
        self.backButton.clicked.connect(searchAnimals.reject)

        self.retranslateUi(searchAnimals)
        QtCore.QMetaObject.connectSlotsByName(searchAnimals)
        self.tableheader = self.animalTable.horizontalHeader()
        self.tableheader.sectionClicked.connect(self.sortbyHeader)
        self.loadBox()

    def retranslateUi(self, searchAnimals):
        _translate = QtCore.QCoreApplication.translate
        searchAnimals.setWindowTitle(_translate("searchAnimals", "Dialog"))
        self.typeLabel.setText(_translate("searchAnimals", "Type"))
        item = self.animalTable.horizontalHeaderItem(0)
        item.setText(_translate("searchAnimals", "Name"))
        item = self.animalTable.horizontalHeaderItem(1)
        item.setText(_translate("searchAnimals", "Species"))
        item = self.animalTable.horizontalHeaderItem(2)
        item.setText(_translate("searchAnimals", "Exhibit"))
        item = self.animalTable.horizontalHeaderItem(3)
        item.setText(_translate("searchAnimals", "Age"))
        item = self.animalTable.horizontalHeaderItem(4)
        item.setText(_translate("searchAnimals", "Type"))
        self.ageLabel.setText(_translate("searchAnimals", "Age"))
        self.speciesLabel.setText(_translate("searchAnimals", "Species"))
        self.searchButton.setText(_translate("searchAnimals", "Search"))
        self.detailLabel.setText(_translate("searchAnimals", "Animals"))
        self.exhibitLabel.setText(_translate("searchAnimals", "Exhibit"))
        self.nameLabel.setText(_translate("searchAnimals", "Name"))
        self.amaxLabel.setText(_translate("searchAnimals", "Max"))
        self.typeBox.setItemText(1, _translate("searchAnimals", "mammal"))
        self.typeBox.setItemText(2, _translate("searchAnimals", "bird"))
        self.typeBox.setItemText(3, _translate("searchAnimals", "amphibian"))
        self.typeBox.setItemText(4, _translate("searchAnimals", "reptile"))
        self.typeBox.setItemText(5, _translate("searchAnimals", "fish"))
        self.typeBox.setItemText(6, _translate("searchAnimals", "inverterbrate"))
        self.aminLabel.setText(_translate("searchAnimals", "Min"))
        self.zooLabel.setText(_translate("searchAnimals", "Atlanta Zoo"))
        self.backButton.setText(_translate("searchAnimals", "Back"))

        self.loadAnimal()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchAnimals = QtWidgets.QDialog()
    ui = Ui_searchAnimals("Junho")
    ui.setupUi(searchAnimals)
    searchAnimals.show()
    sys.exit(app.exec_())

